(ns mongol-ime.position)

(defn adjust-position [{:keys [cursor overlay-size window-size]}]
  (let [{:keys [x y]} cursor
        {:keys [w h]} overlay-size
        {:keys [ww wh]} window-size
        padding 8
        ;; 如果超出右边界，向左翻转
        nx (if (> (+ x w padding) ww)
             (- x w)
             x)
        ;; 如果超出下边界，向上显示
        ny (if (> (+ y h padding) wh)
             (- y h)
             y)]
    {:x (max padding nx)
     :y (max padding ny)}))

